### ISSUE TITLE
Morning session review feedback

### ISSUE THREAD

**Issue by lexoxo** [lexoxo/Portfolio-setup-and-mobile-version-skeleton#3]
# the aim is to give additional inset to improve the code

**Comment by EzekielUtshudi** [comment]
Well done, Your work was well structured but lease next time have more descriptive comments to help others understand your codes.

**Comment by lexoxo** [comment]
@EzekielUtshudi Thanks for the feedback 👌

**Comment by Andrew-Ccoder** [comment]
good job man.

**Comment by HamzaAnwar1998** [comment]
Everything is perfect! The code is clean, design is very nice but there is one thing that I think you can improve is you can wrap all of your code in the main tag so you can manipulate your CSS using the class of the main tag if you may have need sometimes in future. I don't think it is a nice idea to use a body tag for styling.
